---
title: "Untitled"
author: "Korawat Tanwisuth"
date: "February 25, 2018"
output: html_document
---

```{r}
# You need to set your own directory

# read in the data
data = read.csv("N100StkPrices.csv", header = TRUE)


# clean up data
data = na.omit(data)
ticker = data$TICKER

# spun off MDLZ
delete = seq(1, dim(data)[1])[ticker == "MDLZ"]
data = data[-delete, ]

date = apply(as.matrix(data$date), MARGIN = 1, FUN = "toString")
date = as.Date(date, "%Y%m%d")
ticker = data$TICKER
price = data$PRC
shares = data$SHROUT


# Accounting for changes in ticker names



# KFT changed to KRFT in Oct 2012.
ticker[ticker == "KFT"] = "KRFT"

# SXCI changed to CTRX in Jul 2012.
ticker[ticker == "SXCI"] = "CTRX"

# HANS changed to MNST in Jan 2012.
ticker[ticker == "HANS"] = "MNST"




# convert prices to a matrix, arranged by rows of dates and columns of tickers
unique_dates = sort(unique((date)))
unique_tickers = sort(unique(ticker))

priceMat = matrix(NA, length(unique_dates), length(unique_tickers))
sharesMat = matrix(0, length(unique_dates), length(unique_tickers))




for (i in 1:length(unique_tickers)) {
  tic = unique_tickers[i]
  idx = is.element(unique_dates, date[ticker == tic])
  
  priceMat[idx, i] = price[ticker == tic]
  sharesMat[idx, i] = shares[ticker == tic]
}

rownames(priceMat) = as.character(unique_dates)
rownames(sharesMat) = as.character(unique_dates)

rm(list = c("data", "delete", "i", "idx", "price", "shares", "tic", "ticker", "date"))



# Read Monthly Data -------------------------------------------------------

# read in the data
mdata = read.csv("N100Monthly.csv", header = TRUE, stringsAsFactors = FALSE)

# clean up data
mdate = apply(as.matrix(mdata$date), MARGIN = 1, FUN = "toString")
mdate = as.Date(mdate, "%Y%m%d")

mticker = mdata$TICKER
mprice = mdata$PRC
mshares = mdata$SHROUT
mticker[mticker == "FOXA"] = "NWSA"


unique_mdates = sort(unique((mdate)))
unique_mtickers = sort(unique(mticker))

idx = is.element(unique_mtickers, unique_tickers)

# if (!all(idx)) {
#   print("Warning: Some tickers seem to be missing")
# }

monthlyPriceMat = matrix(NA, length(unique_mdates), length(unique_tickers))

for (i in 1:length(unique_tickers)) {
  tic = unique_tickers[i]
  idx = is.element(unique_mdates, mdate[mticker == tic])
  monthlyPriceMat[idx, i] = mprice[mticker == tic]
}

rm("mdata", "i", "idx", "mprice", "mshares", "mticker", "tic", "mdate")
```

#1.

```{r}
daily_return <- matrix(0, ncol = ncol(priceMat), nrow=nrow(priceMat)-1)
for(i in 1:ncol(priceMat)){
    today_price <- priceMat[,i]
    next_price <- c(today_price[2:length(today_price)],0)
    daily_return[,i] <- ((next_price-today_price)/today_price)[-length(next_price)]
}
rownames(daily_return) <- as.character(unique_dates[2:length(unique_dates)])
colnames(daily_return) <- unique_tickers
```

#2.
```{r}
similarity <- cor(daily_return,use ="pairwise.complete.obs")
```

#3
```{r}

library(lpSolve)
constructFund<- function(rho, q, priceMat, sharesMat, unique_tickers, unique_dates){
    n <- nrow(rho)
    num_constraints <- ((n+1)+n*n)
    num_decisions <- (n*n)+n
    A <- matrix(0,nrow = num_constraints, ncol=(n*n)+n)
    z <- c(matrix(rho, ncol =1),rep(0,n))
    ##y q constraint
    A[1,] <- c(rep(0,n*n),rep(1,n))
    ##x 1 constraint
    pick_one <- matrix(0, ncol=n*n, nrow = n)
    for(i in 1:nrow(pick_one)){
        start <- ((n*(i-1))+1)
        end <- start+n-1
        pick_one[i,start:end] <- rep(1,n)
    }
    A[2:(2+n-1),1:(n*n)] <- pick_one
    ##x y constraint
    y_mat <- NULL
    for(i in 1:n){
        temp <- diag(-1,n)
        y_mat <- rbind(y_mat,temp)
    }
    
    A[(n+2):nrow(A),1:num_decisions] <- cbind(diag(1,n*n),y_mat)
    signs <- c(rep("=",n+1),rep("<=",n*n))
    b <- c(q,rep(1,n), rep(0,n*n))
    
    ans <- lp("max",z,A,signs,b,binary.vec = 1:num_decisions)
    
    sol <- ans$solution
    mat_sol <- matrix(sol[1:(length(sol)-n)],ncol = n ,nrow =n, byrow = TRUE)
    capitalization <- priceMat[nrow(priceMat),]*sharesMat[nrow(sharesMat),]
    weights <- capitalization/sum(capitalization)
    final_sol <- NULL
    for(j in 1:n){
        w_j <- sum(weights*mat_sol[,j])
        final_sol <- c(final_sol, w_j)
    }
    
    return(final_sol)
}

test_similartity = similarity[1:10, 1:10]
test_priceMat = priceMat[1:10, 1:10]
test_sharesMat = sharesMat[1:10, 1:10]
constructFund(test_similartity, 5, test_priceMat, test_sharesMat, unique_tickers, unique_dates)
```

#4.
```{r}
monthly_return <- matrix(0, nrow=nrow(monthlyPriceMat)-1, ncol = ncol(monthlyPriceMat))
# for(i in 1:ncol(monthlyPriceMat)){
#     monthly_prices <- monthlyPriceMat[,i]
#     next_month_price <- c(monthly_prices[2:length(monthly_prices)],0)
#     return <- ((next_month_price-monthly_prices)/monthly_prices)[-length(next_month_price)]
#     monthly_return[,i] <- return
# }
investment <- 1000000
investment_weights <- constructFund(similarity,25,priceMat,sharesMat,unique_tickers,unique_dates)
investment_amount <- investment*investment_weights
total_return <- rep(0,nrow(monthly_return)-1)
n_shares <- investment_amount/priceMat[nrow(priceMat),]
for(i in 1:ncol(monthly_return)){
    monthly_prices <-  monthlyPriceMat[,i]
    ret <- c(monthly_prices[2:length(monthly_prices)],0) - monthly_prices
    monthly_return[,i] <- ret[-length(ret)]
}
for(i in 1:nrow(monthly_return)){
    total_return[i] <- sum(n_shares *monthly_return[i,])
}
price_nasdaq_dec <- 2660.93
nas_shares <- investment/price_nasdaq_dec

nasdaq = c(2731.53, 2738.58, 2818.69, 2887.44, 2981.76,
2909.60, 3090.19, 3073.81, 3218.20, 3377.73, 3487.82, 3592.00)
nas_daq_return <- NULL
for(i in 1:(length(nasdaq)-1)){
    nas_daq_return <- c(nas_daq_return, nasdaq[i+1]-nasdaq[i])
}
total_nas_return <- nas_daq_return*nas_shares
plot(1:11,total_return, type="o")
lines(total_nas_return, tpye = "o")
```

```{r}
#% Return
monthly_return <- matrix(0, nrow=nrow(monthlyPriceMat)-1, ncol = ncol(monthlyPriceMat))
for(i in 1:ncol(monthlyPriceMat)){
    monthly_prices <- monthlyPriceMat[,i]
    next_month_price <- c(monthly_prices[2:length(monthly_prices)],0)
    return <- ((next_month_price-monthly_prices)/monthly_prices)[-length(next_month_price)]
    monthly_return[,i] <- return
}
investment <- 1000000
# investment_weights <- constructFund(similarity,25,priceMat,sharesMat,unique_tickers,unique_dates)
investment_amount <- investment*investment_weights
total_return <- rep(0,nrow(monthly_return)-1)
for(i in 1:nrow(monthly_return)){
    total_return[i] <-sum(monthly_return[i,]*investment_amount)
    
}
price_nasdaq_dec <- 2660.93
nas_shares <- investment/price_nasdaq_dec

nasdaq = c(2731.53, 2738.58, 2818.69, 2887.44, 2981.76,
2909.60, 3090.19, 3073.81, 3218.20, 3377.73, 3487.82, 3592.00)
nas_daq_return <- NULL
for(i in 1:(length(nasdaq)-1)){
    nas_daq_return <- c(nas_daq_return, nasdaq[i+1]-nasdaq[i])
}
total_nas_return <- nas_daq_return*nas_shares
plot(total_return, type="o")
lines(total_nas_return, type = "o")
```


```{r}
 mean_price <- apply(priceMat,2,mean)
 a<- dist(mean_price)
 n <- length(mean_price)
 s <- matrix(0,n,n)
 for(i in 1:ncol(s)){
     s[,i] <- abs(mean_price - mean_price[i])
 }
 flip <- function(x){
     return(1/x)
 }
sim <- apply(s, 2,flip)
diag(sim)<- 1
sim[is.na(sim)] <- 0
investment_weights<- constructFund(sim,25,priceMat,sharesMat,unique_tickers,unique_dates)
t<- 1
for(i in 1:ncol(priceMat)){
    for(j in t:ncol(priceMat)){
        ss <- sum((priceMat[,i]-priceMat[,j])^2)
        print(ss)
        s[i,j] <- 1/ss
    }
    t = t+1
}

```


